name: CI               # ワークフロー名、GitHub画面に表示

on: [push, pull_request]  # mainへのpush と PR 作成/更新で実行

jobs:
  test:
    runs-on: ubuntu-latest     # 実行OS…最初はこれで十分
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3   # コードを仮想マシンにクローン

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"    # ★必要なら 3.10 などに変更

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]     # pyproject.toml の [dev] をインストール
          echo "PYTHONPATH=${{ github.workspace }}" >> $GITHUB_ENV   # ★ここを追加

      - name: Run tests
        run: pytest -q
